apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
  namespace: poc-psql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
      